name: Ruff check and format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ruff:
    name: Run Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Ruff Check
        run: ruff check .

      - name: Run Ruff Format
        run: ruff format .
